@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ultreon.randomthingz.tileentity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;