modLoader="javafml" #mandatory
loaderVersion="[39,)"
issueTrackerURL="https://github.com/QTechCommunity/RandomThingz/issues" #optional
license="""(C) Copyright 2020 - QTech Community.
This project is licensed under the CC BY-NC-SA 4.0 license.
See this link for the full license: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
"""

[[mods]] #mandatory
modId="randomthingz" #mandatory
version="$$MOD_VERSION$$" #mandatory
displayName="Random Thingz: Main Mod" #mandatory
#updateJSONURL="http://myurl.me/" #optional. Todo: add update URL for Forge.
displayURL="https://github.com/Ultreon/RandomThingz" #optional
logoFile= "randomthingz.png" #optional
credits="Qboi123, Laz The Artist, INDUSTRIALIST, StormDragon77, FatCow Web (TM), JustinRustin, Gengar, Miep_HD, Giovanni_5656, F1ash, Kai1907, Shadow_236, Nate the Penguin, un_roman, kekkman, sirkomplete, Etaris, Robert0213" #optional
authors="Qboi123, Laz The Artist" #optional
itemIcon="randomthingz:infinity_ingot"
description='''
§l§nRandom Thingz§r
  §7§oProbably just another random things mod.§r

  §7§lStatus:§r §o§aRelease§r

  §oFor some of you, knows the The World Items mod and it's versions 1, 2 and 3.§r
  §oBut now knowing more about creating mods, there's a new new version of the mod with a brand new name.§r
  §oThe mod has been rewritten in pure Java. And adding already more things that before: The Random Thingz Project!§r

§l§nLinks:§r
  MultiTeam Discord Server: https://discord.gg/rudHdrJ
  QTech Community Discord Server: https://www.discord.gg/WePT9v2CmQ
  QTech Community home page: https://quintenjungblut.wixsite.com/qplaysoftware

§l§nSource code:§r
  https://github.com/QTechCommunity/RandomThingz

§l§nBugs / Feature requests§r
  §cIn Alpha / Beta releases stuff might change or break, it's recommended to use them for testing purposes only.§r
  If there's a problem with the mod: don't post the crash report in the comments, but post it on the issue tracker here.
  If there's no crash report but it still crashes, post the debug.log file in your .minecraft/logs folder to the issue tracker.
  If there's no crash report and there's no crash in the debug.log, then there's probably a problem with your Java / Computer.

  If you want to request a feature you can also do it here.

§l§nCredits:§r
  §l"Modern Sofa" by JustinRustin (Modern Sofa)§r
  Available for download at https://blockmodels.com/model/361/ §r

  §l"Club" by Gengar (Club)§r
  §oAvailable for download at https://blockmodels.com/model/496/ §r

  §l"Table with tablecloth" by Miep_HD (Table)§r
  §oAvailable for download at https://blockmodels.com/model/668/ §r

  §l"Healing Potion" by Gengar (Healing Potion)§r
  §oAvailable for download at https://blockmodels.com/model/531/ §r

  §l"Improved PC Gamer" by Giovanni_5656 (Game PC)§r
  §oAvailable for download at https://blockmodels.com/model/339/ §r

  §l"Router" by F1ash (Router)§r
  §oAvailable for download at https://blockmodels.com/model/331/ §r

  §l"Wooden Box" by F1ash (Crate)§r
  §oAvailable for download at https://blockmodels.com/model/330/ §r

  §l"Minecraft Dungeons Textures for Minecraft Java Edition" by Kai1907 and Shadow_236§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/minecraft-dungeons-textures-for-minecraft-java-edition/ §r

  §l"Fresh CIT v1.2" by FreshLX§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/fresh-cit-v1-0/ §r

  §l"GearPlus 1.16!" by Nate the Penguin§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/vanilla-more-items-armor-shields-and-more/ §r

  §l"GearPlus - Terraria Edition" by Nate the Penguin§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/gearplus-terraria-edition/ §r

  §l"Cocoa Cake" by The Sailor§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/cocoa-cake/ §r

  §l"Bone meal into Fertilizer" by Sucro120§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/bone-meal-into-fertilizer/ §r

  §l"ActuallyAssets - Hypixel Skyblock v1.6.6" by MotorGorilla1§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/actuallyassets-hypixel-skyblock-v-10/ §r

  §l"MoobLoom Update(Optifine)" by un_roman§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/moobloom-update/ §r

  §l"Avocados" by kekkman§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/avocados-4860171/ §r

  §l"Vanilla+ | 225 Custom Bookshelves Add-On" by sirkomplete, Etaris and Robert0213§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/vanilla-225-custom-bookshelves-add-on/ §r

  §l"Shinier Rails" by StormDragon77§r
  §oAvailable for download at https://www.planetminecraft.com/texture-pack/shinier-rails/ §r

  §l"FatCow Icons" by FatCow Web (TM)§r
  §oAvailable for download at http://www.fatcow.com/free-icons/ §r

  §lSapphire and Amber: Ore, Gem and Block texture by INDUSTRIALIST§r
  §oAvailable on DeviantArt: https://www.deviantart.com/alex-moshan §r

  §l=--------------------------=§r
  §oQForgeUtils 1.0§r
  §l§n=--------------------------=§r
  §oDownload not available!§r
'''

[[mods]] #mandatory
modId="qtexturedmodels" #mandatory
version="1.0-release1" #mandatory
displayName="Random Thingz: Textured Models Mod" #mandatory
credits="Thanks for many help goes to McJty and the Forge Forum Team" #optional
authors="PianoManu, Qboi123" #optional
itemIcon="qtexturedmodels:hammer"
description='''
This Mod is partially forked from: https://github.com/PianoManu/QTextureModels
The mod was merged after the base essentials of Random Thingz were created.

Original description:
Fork Mod of Carpenter's Blocks Mod created by Mineshopper (owner of the idea) for older versions of Minecraft.
I created this fork because friends of mine would like to play this mod on 1.15 (and me too).

Right now there is no guide for this mod, so here is one in small form:
- Right-Click on a frame block to give it the texture of the block you clicked it with
- Right-Click with the hammer to get the block back out of the frame (you can change this feature in the config file, so that you only need an empty hand and Sneak-Rightclick)
- For blocks with different textures on each side, you can select the texture you want using the texture wrench
- Let the blocks glow by right-clicking them with glowstone dust or coal/charcoal
- You can also change the appearance of a block by right-clicking it with the chisel and the paintbrush

Have fun!
'''

[[mods]]
modId="qfilters"
version="1.3.0"
displayName="Random Thingz: Filters Mod"
logoFile="filters.png"
credits=""
authors="MrCrayfish, Qboi123"
license="""
GNU LESSER GENERAL PUBLIC LICENSE, Version 2.1
https://raw.githubusercontent.com/MrCrayfish/Filters/master/LICENSE.txt

Forked from here: https://github.com/MrCrayfish/Filters
"""
description='''
A mod that improves the Creative GUI by introducing filters based on tags
Ported to 1.16.3 by Qboi123.
'''

[[dependencies.qfilters]] #optional
modId="forge"
mandatory=true
versionRange="[39,)"
ordering="NONE"
side="CLIENT"
[[dependencies.qfilters]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.18.2)"
ordering="NONE"
side="CLIENT"

[[dependencies.qtexturedmodels]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[39,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.qtexturedmodels]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.18.2)"
ordering="NONE"
side="BOTH"


[[dependencies.randomthingz]]
modId="qfilters"
mandatory=true
versionRange="1.3.0"
ordering="BEFORE"
side="CLIENT"
[[dependencies.randomthingz]]
modId="qtexturedmodels"
mandatory=true
versionRange="1.3.0"
ordering="NONE"
side="BOTH"
[[dependencies.randomthingz]]
modId="umodlib"
mandatory=true
versionRange="[1.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.randomthingz]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[39,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.randomthingz]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.18.2)"
ordering="NONE"
side="BOTH"
