@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ultreon.randomthingz.block.advanced;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;