@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ultreon.randomthingz.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;