@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ultreon.randomthingz.block.machines.arcaneescalator;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;