@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.qtech.randomthingz.block.machines.arcaneescalator;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;