@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.silentchaos512.lib.collection;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;