@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.ultreon.randomthingz;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;